### ISSUE TITLE
Java language version

### ISSUE THREAD

**Issue by LeanderK** [codecombat/cashew#5]
what Java language version are you targeting?
Can you successfully parse lambdas and method references?
Thank you

**Comment by lucasfarias** [comment]
Hello @LeanderK!

The target is the AP subset, it's now described [here](https://secure-media.collegeboard.org/digitalServices/pdf/ap/ap-computer-science-a-java-subset.pdf) I'm not sure if they changed the subset from February but I don't think so, I checked quickly and it looks like the same 😄 !

So no lambdas…

Also as far as I remember there's an issue with private methods because JavaScript (ECMAScript 5 original target) used to handle privates in a very differently from how JAVA handles privates…

**Comment by LeanderK** [comment]
ok, thank you for your Help!
